// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQB-sw000wMeQ8X5xIm4sSdTmnpdvIBu0',
    appId: '1:286338874029:web:842c69e67666b8bf432424',
    messagingSenderId: '286338874029',
    projectId: 'smart-farm-3db28',
    authDomain: 'smart-farm-3db28.firebaseapp.com',
    storageBucket: 'smart-farm-3db28.appspot.com',
    measurementId: 'G-PQTDKMB5Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHLUNNz78LHDiYdDlZjuAqq2e9GRAlYJY',
    appId: '1:286338874029:android:0fed5062ef8bf4e8432424',
    messagingSenderId: '286338874029',
    projectId: 'smart-farm-3db28',
    storageBucket: 'smart-farm-3db28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVW7GcLHuYNXtjPok88DAO8LU5s7zjEo',
    appId: '1:286338874029:ios:35fb1a50b5051b3d432424',
    messagingSenderId: '286338874029',
    projectId: 'smart-farm-3db28',
    storageBucket: 'smart-farm-3db28.appspot.com',
    iosClientId: '286338874029-bq61rilahic84tch89e1f23q9lrcm6vt.apps.googleusercontent.com',
    iosBundleId: 'id.co.sadigit.smartfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALVW7GcLHuYNXtjPok88DAO8LU5s7zjEo',
    appId: '1:286338874029:ios:35fb1a50b5051b3d432424',
    messagingSenderId: '286338874029',
    projectId: 'smart-farm-3db28',
    storageBucket: 'smart-farm-3db28.appspot.com',
    iosClientId: '286338874029-bq61rilahic84tch89e1f23q9lrcm6vt.apps.googleusercontent.com',
    iosBundleId: 'id.co.sadigit.smartfarm',
  );
}
